global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Client.Models;
global using Client.Presentation;
global using Client.DataContracts;
global using Client.DataContracts.Serialization;
global using Client.Services.Caching;
global using Client.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
