FROM lukemathwalker/cargo-chef:latest-rust-1.77.1 AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
RUN cargo install --path .

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /usr/local/cargo/bin/server /usr/local/bin/server
ENV ROCKET_ADDRESS=0.0.0.0
EXPOSE 8000
CMD ["server"]